//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElEscribaDelDJ {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class ConfiguracionAplicacion : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfiguracionAplicacion defaultInstance = ((ConfiguracionAplicacion)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfiguracionAplicacion())));
        
        public static ConfiguracionAplicacion Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ES")]
        public string Idioma {
            get {
                return ((string)(this["Idioma"]));
            }
            set {
                this["Idioma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecordarUsuario {
            get {
                return ((bool)(this["RecordarUsuario"]));
            }
            set {
                this["RecordarUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecordarLogin {
            get {
                return ((bool)(this["RecordarLogin"]));
            }
            set {
                this["RecordarLogin"] = value;
            }
        }
    }
}
